

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhuyenMai;
import reponsitory.KhuyenMaiRepository;
import java.util.Calendar;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.time.LocalDate;

/**
 *
 * @author THANH
 */
public class panelKhuyenMai extends javax.swing.JPanel {

    DefaultTableModel model;
    KhuyenMaiRepository kr = new KhuyenMaiRepository();
    int i =-1;

    /**
     * Creates new form panelKhuyenMai
     */
    public panelKhuyenMai() {
        initComponents();
        kr.updateTrangThaiBD();
        kr.updateTrangThai();
        kr.updateTrangThaikt2();
        kr.updateTrangThaikt3();
        fillTable(kr.getAll());
        txtNgayBD.getDateEditor().addPropertyChangeListener("date", evt -> {
            if ("date".equals(evt.getPropertyName())) {
                if (txtNgayBD.getDate().after(Calendar.getInstance().getTime())) {
                    cboTrangThaiVoucher.setSelectedIndex(0);
                } else {
                    cboTrangThaiVoucher.setSelectedIndex(1);
                }
            }
        });
        
         addPlaceHolderStyle(txtTimKiemVoucher);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVoucher = new javax.swing.JPanel();
        btnClearVoucher = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        cboTrangThaiVoucher = new javax.swing.JComboBox<>();
        jLabel70 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtGhiChuVoucher = new javax.swing.JTextArea();
        txtNgayBD = new com.toedter.calendar.JDateChooser();
        txtNgayKT = new com.toedter.calendar.JDateChooser();
        btnSuaVoucher = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        btnThemVoucher = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        txtMaVoucher = new javax.swing.JTextField();
        txtTenVoucher = new javax.swing.JTextField();
        cboMucGiamGia = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        txtTimKiemVoucher = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        jLabel75 = new javax.swing.JLabel();

        pnlVoucher.setBackground(new java.awt.Color(255, 255, 255));

        btnClearVoucher.setBackground(new java.awt.Color(255, 0, 51));
        btnClearVoucher.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClearVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnClearVoucher.setText("Clear");
        btnClearVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearVoucherActionPerformed(evt);
            }
        });

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel67.setText("Ngày hết hạn");

        jLabel68.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel68.setText("Ngày bắt đầu");

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel69.setText("Trạng thái");

        cboTrangThaiVoucher.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cboTrangThaiVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa áp dụng", "Đang áp dụng", "Đã hết hạn" }));
        cboTrangThaiVoucher.setEnabled(false);
        cboTrangThaiVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrangThaiVoucherActionPerformed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel70.setText("Ghi chú");

        txtGhiChuVoucher.setColumns(20);
        txtGhiChuVoucher.setRows(5);
        jScrollPane14.setViewportView(txtGhiChuVoucher);

        txtNgayBD.setDateFormatString("dd-MM-yyyy");
        txtNgayBD.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtNgayBDComponentAdded(evt);
            }
        });
        txtNgayBD.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNgayBDAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                txtNgayBDAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNgayBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayBDMouseClicked(evt);
            }
        });
        txtNgayBD.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtNgayBDComponentMoved(evt);
            }
        });
        txtNgayBD.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNgayBDCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtNgayBDInputMethodTextChanged(evt);
            }
        });
        txtNgayBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNgayBDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNgayBDKeyReleased(evt);
            }
        });

        txtNgayKT.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTrangThaiVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(jLabel70))
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane14))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTrangThaiVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSuaVoucher.setBackground(new java.awt.Color(255, 0, 51));
        btnSuaVoucher.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaVoucher.setText("Sửa");
        btnSuaVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaVoucherActionPerformed(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel71.setText("Tạo chương trình khuyến mãi");

        btnThemVoucher.setBackground(new java.awt.Color(255, 0, 51));
        btnThemVoucher.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnThemVoucher.setText("Thêm");
        btnThemVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVoucherActionPerformed(evt);
            }
        });

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel72.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel72.setText("Mã khuyễn mãi");

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel73.setText("Tên chương trình khuyến mãi ( Áp dụng tất cả sản phẩm )");

        jLabel74.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel74.setText("Mức giá giảm (%)");

        cboMucGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%", "20%", "30%", "35%", "45%", "50%" }));
        cboMucGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMucGiamGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMaVoucher)
                        .addComponent(txtTenVoucher)
                        .addComponent(jLabel73)
                        .addComponent(jLabel74)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboMucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel74)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboMucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTimKiemVoucher.setText("Tìm kiếm");
        txtTimKiemVoucher.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemVoucherCaretUpdate(evt);
            }
        });
        txtTimKiemVoucher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemVoucherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemVoucherFocusLost(evt);
            }
        });
        txtTimKiemVoucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemVoucherKeyReleased(evt);
            }
        });

        tblVoucher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc", "Mức giảm giá", "Trạng thái ", "Ghi chú"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(tblVoucher);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(txtTimKiemVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel75.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel75.setText("Danh sách Vouncher");

        javax.swing.GroupLayout pnlVoucherLayout = new javax.swing.GroupLayout(pnlVoucher);
        pnlVoucher.setLayout(pnlVoucherLayout);
        pnlVoucherLayout.setHorizontalGroup(
            pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVoucherLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVoucherLayout.createSequentialGroup()
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVoucherLayout.createSequentialGroup()
                                .addComponent(btnThemVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(btnSuaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(btnClearVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(pnlVoucherLayout.createSequentialGroup()
                .addGroup(pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVoucherLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlVoucherLayout.setVerticalGroup(
            pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVoucherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel71)
                .addGap(28, 28, 28)
                .addGroup(pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVoucherLayout.createSequentialGroup()
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1177, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearVoucherActionPerformed
        txtGhiChuVoucher.setText("");
        txtMaVoucher.setText("");
        txtTenVoucher.setText("");
        txtNgayBD.setDate(Calendar.getInstance().getTime());
        txtNgayKT.setDate(Calendar.getInstance().getTime());
        txtTimKiemVoucher.setText("");
        fillTable(kr.getAll());
    }//GEN-LAST:event_btnClearVoucherActionPerformed

    private void btnSuaVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaVoucherActionPerformed
        i = tblVoucher.getSelectedRow();
        if(i==-1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần sửa");
            return;
        }
        if(check()){
            String a = (String) tblVoucher.getValueAt(tblVoucher.getSelectedRow(),0 );
            if(txtMaVoucher.getText().equals(a)){
                if (kr.updateKM(readForm(),a ) != 0) {
                    JOptionPane.showMessageDialog(this, "OK");
                    fillTable(kr.getAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Fails");
                }
            }else{
                if (kr.getMa(txtMaVoucher.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Mã đã được dùng cho chương trình khuyến mãi khác");
            } else {
                if (kr.updateKM(readForm(),a ) != 0) {
                    JOptionPane.showMessageDialog(this, "OK");
                    fillTable(kr.getAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Fails");
                }
            }
            }
        }
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        String ma = txtMaVoucher.getText();
//        String ten = txtTenVoucher.getText();
//        if (txtNgayBatDau.getDate() == null || txtNgayHetHan.getDate() == null) {
//            JOptionPane.showMessageDialog(this, "Ngày không để trống");
//        } else {
//            String ngayBD = sdf.format(txtNgayBatDau.getDate());
//            String ngayHH = sdf.format(txtNgayHetHan.getDate());
//            int trangThai = 0;
//            if (cbbTrangThaiVoucher.getSelectedItem().equals("Đang áp dụng")) {
//                trangThai = 0;
//            } else {
//                trangThai = 1;
//            }
//            Double mucGiam = 0.0;
//            String gg = cbbMucGiamGia.getSelectedItem().toString();
//            if (gg == "5%") {
//                mucGiam = 0.95;
//            } else if (gg == "10%") {
//                mucGiam = 0.9;
//            } else if (gg == "15%") {
//                mucGiam = 0.85;
//            } else if (gg == "20%") {
//                mucGiam = 0.8;
//            } else if (gg == "25%") {
//                mucGiam = 0.75;
//            } else if (gg == "30%") {
//                mucGiam = 0.7;
//            } else if (gg == "35%") {
//                mucGiam = 0.65;
//            } else if (gg == "40%") {
//                mucGiam = 0.6;
//            } else if (gg == "45%") {
//                mucGiam = 0.55;
//            } else if (gg == "50%") {
//                mucGiam = 0.50;
//            }
//
//            String ghiChu = txtGhiChuVoucher.getText();
//
//            if (CheckDLVC() == false) {
//
//                var temp = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa");
//                if (temp == 0) {
//
//                    Voucher v = new Voucher(ma, ten, mucGiam, Date.valueOf(ngayBD), Date.valueOf(ngayHH), ghiChu, trangThai);
//                    JOptionPane.showMessageDialog(this, vcs.update(v, ma));
//                    listVoucherCM = vcs.getAllCustom();
//                    loadData(listVoucherCM);
//
//                }
//            }
//        }
    }//GEN-LAST:event_btnSuaVoucherActionPerformed

    private void btnThemVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVoucherActionPerformed
        if (check()) {
            String a = txtMaVoucher.getText();
            if (kr.getMa(a) != null) {
                JOptionPane.showMessageDialog(this, "Mã đã được dùng cho chương trình khuyến mãi khác");
            } else {
                if (kr.addKM(readForm()) != 0) {
                    JOptionPane.showMessageDialog(this, "OK");
                    fillTable(kr.getAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Fails");
                }
            }
        }
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        String ma = txtMaVoucher.getText();
//        String ten = txtTenVoucher.getText();
//        if (txtNgayBatDau.getDate() == null || txtNgayHetHan.getDate() == null) {
//            JOptionPane.showMessageDialog(this, "Ngày không để trống");
//        } else {
//            java.util.Date bd = (java.util.Date) txtNgayBatDau.getDate();
//            java.util.Date kt = (java.util.Date) txtNgayHetHan.getDate();
//            Calendar c1 = Calendar.getInstance();
//            Calendar c2 = Calendar.getInstance();
//            c1.setTime(bd);
//            c2.setTime(kt);
//
//            long noDay = (c2.getTime().getTime() - c1.getTime().getTime()) / (24 * 3600 * 1000);
//            if (noDay < 0) {
//                JOptionPane.showConfirmDialog(this, "Ngày hết hạn phải lớn hơn ngày bắt đầu");
//            } else {
//                String ngayBD = sdf.format(txtNgayBatDau.getDate());
//                String ngayHH = sdf.format(txtNgayHetHan.getDate());
//                int trangThai = 0;
//                if (cbbTrangThaiVoucher.getSelectedItem().equals("Đang áp dụng")) {
//                    trangThai = 0;
//                } else {
//                    trangThai = 1;
//                }
//                Double mucGiam = 0.0;
//                String gg = cbbMucGiamGia.getSelectedItem().toString();
//                if (gg == "5%") {
//                    mucGiam = 0.95;
//                } else if (gg == "10%") {
//                    mucGiam = 0.9;
//                } else if (gg == "15%") {
//                    mucGiam = 0.85;
//                } else if (gg == "20%") {
//                    mucGiam = 0.8;
//                } else if (gg == "25%") {
//                    mucGiam = 0.75;
//                } else if (gg == "30%") {
//                    mucGiam = 0.7;
//                } else if (gg == "35%") {
//                    mucGiam = 0.65;
//                } else if (gg == "40%") {
//                    mucGiam = 0.6;
//                } else if (gg == "45%") {
//                    mucGiam = 0.55;
//                } else if (gg == "50%") {
//                    mucGiam = 0.50;
//                }
//
//                String ghiChu = txtGhiChuVoucher.getText();
//
//                if (CheckDLVC() == false && CheckTrungMaVC() == false) {
//
//                    var temp = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm mới");
//                    if (temp == 0) {
//                        Voucher v = new Voucher(ma, ten, mucGiam, Date.valueOf(ngayBD), Date.valueOf(ngayHH), ghiChu, trangThai);
//                        JOptionPane.showMessageDialog(this, vcs.add(v));
//                        listVoucherCM = vcs.getAllCustom();
//                        loadData(listVoucherCM);
//                    }
//                }
//
//            }
//        }
    }//GEN-LAST:event_btnThemVoucherActionPerformed

    private void txtTimKiemVoucherCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemVoucherCaretUpdate
//        loadData(vcs.Search(txtTimKiemVoucher.getText()));
    }//GEN-LAST:event_txtTimKiemVoucherCaretUpdate

    private void txtTimKiemVoucherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemVoucherFocusGained
        // TODO add your handling code here:
        if (txtTimKiemVoucher.getText().equals("Tìm kiếm")) {
            txtTimKiemVoucher.setText(null);
            removePlaceHolderStyle(txtTimKiemVoucher);

        } 
//        txtTimKiemVoucher.setText("");
    }//GEN-LAST:event_txtTimKiemVoucherFocusGained

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
//        int index = tblVoucher.getSelectedRow();
//
//        fillDataVoucher(index);
        showData();
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void cboMucGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMucGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMucGiamGiaActionPerformed

    private void cboTrangThaiVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrangThaiVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTrangThaiVoucherActionPerformed

    private void txtNgayBDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgayBDKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDKeyReleased

    private void txtNgayBDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNgayBDInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDInputMethodTextChanged

    private void txtNgayBDCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNgayBDCaretPositionChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDCaretPositionChanged

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel21MouseClicked

    private void txtNgayBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayBDMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDMouseClicked

    private void txtNgayBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgayBDKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDKeyPressed

    private void txtNgayBDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgayBDAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDAncestorAdded

    private void txtNgayBDAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgayBDAncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDAncestorMoved

    private void txtNgayBDComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNgayBDComponentMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDComponentMoved

    private void txtNgayBDComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtNgayBDComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgayBDComponentAdded

    private void txtTimKiemVoucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemVoucherKeyReleased
        // TODO add your handling code here:
        String a = "%" + txtTimKiemVoucher.getText()+"%";
        fillTable(kr.getSearch(a));
    }//GEN-LAST:event_txtTimKiemVoucherKeyReleased

    private void txtTimKiemVoucherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemVoucherFocusLost
        // TODO add your handling code here:
        if (txtTimKiemVoucher.getText().length() == 0) {
            addPlaceHolderStyle(txtTimKiemVoucher);
            txtTimKiemVoucher.setText("Tìm kiếm");
        } 
    }//GEN-LAST:event_txtTimKiemVoucherFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearVoucher;
    private javax.swing.JButton btnSuaVoucher;
    private javax.swing.JButton btnThemVoucher;
    private javax.swing.JComboBox<String> cboMucGiamGia;
    private javax.swing.JComboBox<String> cboTrangThaiVoucher;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JPanel pnlVoucher;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextArea txtGhiChuVoucher;
    private javax.swing.JTextField txtMaVoucher;
    private com.toedter.calendar.JDateChooser txtNgayBD;
    private com.toedter.calendar.JDateChooser txtNgayKT;
    private javax.swing.JTextField txtTenVoucher;
    private javax.swing.JTextField txtTimKiemVoucher;
    // End of variables declaration//GEN-END:variables

    void fillTable(List<KhuyenMai> listKM) {
        model = (DefaultTableModel) tblVoucher.getModel();
        model.setRowCount(0);
        for (KhuyenMai khuyenMai : listKM) {
            model.addRow(khuyenMai.toDataRow());
        }
    }

    void showData() {
        int i = tblVoucher.getSelectedRow();
        txtMaVoucher.setText((String) tblVoucher.getValueAt(i, 0));
        txtGhiChuVoucher.setText((String) tblVoucher.getValueAt(i, 6));
        txtTenVoucher.setText((String) tblVoucher.getValueAt(i, 1));
        txtNgayBD.setDate((Date) tblVoucher.getValueAt(i, 2));
        txtNgayKT.setDate((Date) tblVoucher.getValueAt(i, 3));
        cboTrangThaiVoucher.setSelectedItem(tblVoucher.getValueAt(i, 5));
        cboMucGiamGia.setSelectedItem(tblVoucher.getValueAt(i, 4));
    }

        KhuyenMai readForm() {
        String ma = txtMaVoucher.getText();
        String ten = txtTenVoucher.getText();
        Date BD = txtNgayBD.getDate();
        Date KT = txtNgayKT.getDate();
        String gg = (String) cboMucGiamGia.getSelectedItem();
        String tt = (String) cboTrangThaiVoucher.getSelectedItem();
        String gc = txtGhiChuVoucher.getText();
        return new KhuyenMai(ma, ten, BD, KT, gg, tt, gc);
    }

    boolean check() {
        if (txtMaVoucher.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã Vouncher");
            return false;
        }
        if (txtTenVoucher.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên Vouncher");
            return false;
        }
        Date bd = txtNgayBD.getDate();
        Date kt = txtNgayKT.getDate();
        if (bd == null) {
            JOptionPane.showMessageDialog(this, "Dữ ngày bắt đầu không ổn");
            return false;
        } else {
             LocalDate ngBD = txtNgayBD.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    if(ngBD.isBefore(LocalDate.now())){
        JOptionPane.showMessageDialog(this, "Ngày Bắt đầu phải từ hôm nay trở đi");
        return false;
    }
        }
        if (kt == null) {
            JOptionPane.showMessageDialog(this, "Dữ liệu ngày kết thúc không ổn");
            return false;
        } else {
            if (kt.before(txtNgayBD.getDate())) {
                JOptionPane.showMessageDialog(this, "Ngày kết thúc không được trước ngày bắt đầu");
                return false;
            }
        }
        return true;
    }
    public void addPlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);

    }

    public void removePlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(font.PLAIN | Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.gray);

    }

}
