/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.NhanVienModel;
import service.NhanVienService;

/**
 *
 * @author THANH
 */
public final class panelNhanVien extends javax.swing.JPanel {

    private final NhanVienService service = new NhanVienService();
    private DefaultTableModel tblModel = new DefaultTableModel();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    private int index = -1;

    /**
     * Creates new form panelNhanVien
     */
    public panelNhanVien() {
        initComponents();
        this.fillTable(service.getAll());
        addPlaceHolderStyle(txtTimKiem);
    }

    void setModel(NhanVienModel nv) {
        txtMa.setText(nv.getMa());
        txtTen.setText(nv.getHoTen());

        txtMatKhau.setText(nv.getMatKhau());
        txtNgaySinh.setDate(nv.getNgaySinh());
        txtDiaChi.setText(nv.getDiaChi());
        txtSdtNV.setText(nv.getsDT());

        if (nv.getGioiTinh().equalsIgnoreCase("1")) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
            cboChucVu.setSelectedItem("Nhân viên");
        } else if (nv.getChucVu().equalsIgnoreCase("Quản lý")) {
            cboChucVu.setSelectedItem("Quản lý");
        }
    }

    NhanVienModel getForm() {
        String ma, hoTen, matKhau, sDT, gioiTinh, chucVu;
        Date ngaySinh;
        String diaChi,trangThai="Hoạt động";

        ma = txtMa.getText().trim();
        if (txtMa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mã ");
            return null;
        }
        if (cboChucVu.getSelectedItem().equals("Nhân viên")) {
            chucVu = "Nhân viên";
        } else {
            chucVu = "Quản lý";
        }
        hoTen = txtTen.getText().trim();
        if (hoTen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập họ tên ");
            return null;
        }
        matKhau = txtMatKhau.getText();
        if (matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mật khẩu ");
            return null;
        }
        sDT = txtSdtNV.getText().trim();
        if (sDT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số điện thoại ");
            return null;
        }
        if (rdoNam.isSelected()) {
            gioiTinh = "1";
        } else {
            gioiTinh = "0";
        }

        ngaySinh = txtNgaySinh.getDate();
        if (ngaySinh== null) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập ngày sinh ");
            return null;
        }
        diaChi = txtDiaChi.getText().trim();
        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập địa chỉ ");
            return null;
        }
        return new NhanVienModel(ma, hoTen, matKhau, sDT, gioiTinh, chucVu, ngaySinh, diaChi,trangThai);
    }

    void fillTable(List<NhanVienModel> list) {
        tblModel = (DefaultTableModel) tblList.getModel();
        tblModel.setRowCount(0);
        for (NhanVienModel nv : list) {
            String sex;
            if(nv.getGioiTinh().equals("1")){
                sex="Nam";
            }else{
                sex="Nữ";
            }
            Object toDataRow[] = {nv.getMa(), nv.getHoTen(), sex, nv.getChucVu(), nv.getMatKhau(), sdf.format(nv.getNgaySinh()), nv.getDiaChi(), nv.getsDT(), nv.getTrangThai()};
            tblModel.addRow(toDataRow);
        }
    }
    
      public void addPlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);

    }

    public void removePlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(font.PLAIN | Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.gray);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlNhanVien = new javax.swing.JPanel();
        btnUpdateNV = new javax.swing.JButton();
        btnDeleteNV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClearNV = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lbTenChucVu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbTenCuaHang = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSdtNV = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        btnAddNV = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();

        pnlNhanVien.setBackground(new java.awt.Color(255, 255, 255));

        btnUpdateNV.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdateNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdateNV.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateNV.setText("Update");
        btnUpdateNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateNVMouseEntered(evt);
            }
        });
        btnUpdateNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNVActionPerformed(evt);
            }
        });

        btnDeleteNV.setBackground(new java.awt.Color(255, 204, 0));
        btnDeleteNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDeleteNV.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteNV.setText("Nghỉ việc");
        btnDeleteNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteNVMouseEntered(evt);
            }
        });
        btnDeleteNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setText("Họ Tên");

        btnClearNV.setBackground(new java.awt.Color(255, 204, 0));
        btnClearNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClearNV.setForeground(new java.awt.Color(255, 255, 255));
        btnClearNV.setText("Clear");
        btnClearNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearNVMouseEntered(evt);
            }
        });
        btnClearNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNVActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setText("Giới tính");

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setText("Mật khẩu");

        jLabel12.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel12.setText("Chức Vụ");

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel9.setText("Ngày sinh");

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));
        cboChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboChucVuMouseEntered(evt);
            }
        });
        cboChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChucVuActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel10.setText("Địa chỉ");

        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel11.setText("Sdt");

        txtMa.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N

        txtTen.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N

        txtSdtNV.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdoNamMouseEntered(evt);
            }
        });

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdoNuMouseEntered(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel14.setText("NHÂN VIÊN");

        btnAddNV.setBackground(new java.awt.Color(255, 204, 0));
        btnAddNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddNV.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNV.setText("Add");
        btnAddNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNVMouseEntered(evt);
            }
        });
        btnAddNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNVActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel16.setText("Mã");

        txtNgaySinh.setDateFormatString("dd-MM-yyyy");

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ", "Họ Tên", "Giới Tính", "Chức Vụ", "Mật Khẩu", "Ngày Sinh", "ĐỊa Chỉ", "Số Điện Thoại", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblListnone(evt);
            }
        });
        jScrollPane2.setViewportView(tblList);

        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                .addGap(463, 463, 463)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(99, 99, 99)
                                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addGap(51, 51, 51)
                                                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(cboChucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNhanVienLayout.createSequentialGroup()
                                                            .addComponent(rdoNam)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(rdoNu)))))))
                                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                        .addGap(333, 333, 333)
                                        .addComponent(lbTenCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(btnAddNV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(btnUpdateNV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel12)
                                        .addGap(181, 181, 181)
                                        .addComponent(lbTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel11)))
                                        .addGap(62, 62, 62)
                                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSdtNV, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(txtDiaChi)
                                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btnDeleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(btnClearNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 306, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel8)
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdoNam)
                        .addComponent(rdoNu)))
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlNhanVienLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSdtNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addComponent(lbTenCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateNVMouseEntered
        // TODO add your handling code here:
//        btnUpdateNV.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnUpdateNVMouseEntered

    private void btnUpdateNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNVActionPerformed
        index = tblList.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần sửa !");
        } else {
            if (txtMa.getText().equals(tblList.getValueAt(index, 0))) {
                if (service.update(getForm(), service.idNV(txtMa.getText())) > 0) {
                    JOptionPane.showMessageDialog(this, "sửa thành công");
                    this.fillTable(service.getAll());
                    this.resetForm();
                } else {
                    JOptionPane.showMessageDialog(this, "sửa thất bại");
                    this.resetForm();
                }
            } else {
                String ma = txtMa.getText().trim();
                if (service.checkMa(ma) > 0) {
                    JOptionPane.showMessageDialog(this, "ma " + ma + " da duoc dung cho nhan vien khac");
                    return;
                } else {
                    if (service.update(getForm(), service.idNV(txtMa.getText())) > 0) {
                        JOptionPane.showMessageDialog(this, "sửa thành công");
                        this.fillTable(service.getAll());
                        this.resetForm();
                    } else {
                        JOptionPane.showMessageDialog(this, "sửa thất bại");
                        this.resetForm();
                    }
                }
            }

        }
        
        
    }//GEN-LAST:event_btnUpdateNVActionPerformed

    private void btnDeleteNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNVMouseEntered
        // TODO add your handling code here:
//        btnDeleteNV.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnDeleteNVMouseEntered

    private void btnDeleteNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNVActionPerformed
        index = tblList.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhân viên !");

        } else {
            if (service.upNghiViec(service.idNV(txtMa.getText())) > 0) {
                JOptionPane.showMessageDialog(this, "Thành công");
                this.fillTable(service.getAll());
                this.resetForm();
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
                this.resetForm();
            }
        }

    }//GEN-LAST:event_btnDeleteNVActionPerformed

    private void btnClearNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearNVMouseEntered
        // TODO add your handling code here:
//        btnClearNV.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnClearNVMouseEntered

    private void btnClearNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNVActionPerformed
        this.resetForm();
    }//GEN-LAST:event_btnClearNVActionPerformed
    void resetForm() {

        index = -1;
        txtMa.setText("");
        txtTen.setText("");

        txtMatKhau.setText("");
        txtNgaySinh.setDate(null);
        txtDiaChi.setText("");
        txtSdtNV.setText("");

        rdoNam.setSelected(true);
        cboChucVu.setSelectedItem("Nhân viên");
        tblList.getSelectionModel().clearSelection();

    }
    private void cboChucVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboChucVuMouseEntered
//        cbbChucVu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cboChucVuMouseEntered

    private void cboChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChucVuActionPerformed
        // TODO add your handling code here:
//        if (cbbChucVu.getSelectedIndex() < 0) {
//
//        } else {
//            String maCH = cbbChucVu.getSelectedItem().toString();
//            ChucVu cv = (ChucVu) chucVuService.getOne(maCH);
//            lbTenChucVu.setText(cv.getTen());
//        }
    }//GEN-LAST:event_cboChucVuActionPerformed

    private void rdoNamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNamMouseEntered
//        radioNam.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_rdoNamMouseEntered

    private void rdoNuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNuMouseEntered
//        radioNu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_rdoNuMouseEntered

    private void btnAddNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNVMouseEntered
        // TODO add your handling code here:
//        btnAddNV.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAddNVMouseEntered

    private void btnAddNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNVActionPerformed
        String ma = txtMa.getText().trim();
        if (service.checkMa(ma) > 0) {
            JOptionPane.showMessageDialog(this, "ma " + ma + " da ton tai");
            return;
        }
        if (service.add(getForm()) > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");

            this.fillTable(service.getAll());
            this.resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm lỗi");
        }

    }//GEN-LAST:event_btnAddNVActionPerformed

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        // TODO add your handling code here:
        index = tblList.getSelectedRow();

        NhanVienModel nv = service.getAll().get(index);
        this.setModel(nv);
    }//GEN-LAST:event_tblListMouseClicked

    private void tblListnone(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListnone

    }//GEN-LAST:event_tblListnone

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
        if (txtTimKiem.getText().equals("Tìm kiếm")) {
            txtTimKiem.setText(null);
            removePlaceHolderStyle(txtTimKiem);

        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        // TODO add your handling code here:
        if (txtTimKiem.getText().length() == 0) {
            addPlaceHolderStyle(txtTimKiem);
            txtTimKiem.setText("Tìm kiếm");
        } 
    }//GEN-LAST:event_txtTimKiemFocusLost

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        fillTable(service.search(txtTimKiem.getText()));
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNV;
    private javax.swing.JButton btnClearNV;
    private javax.swing.JButton btnDeleteNV;
    private javax.swing.JButton btnUpdateNV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTenChucVu;
    private javax.swing.JLabel lbTenCuaHang;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMatKhau;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSdtNV;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
