/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChatLieu;
import reponsitory.ChatLieuRepository;
import service.ChatLieuService;

/**
 *
 * @author natsu
 */
public class viewChatLieu extends javax.swing.JFrame {

    private final ChatLieuService chatLieuService = new ChatLieuService();
    private int index = -1;

    /**
     * Creates new form viewChatLieu
     */
    public viewChatLieu() {
        initComponents();
        setLocationRelativeTo(null);
        loadTableChatLieu();
    }

    public void resetInputSPCL() {
        txtMaChatLieu.setText(null);
        txtTenChatLieu.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        txtMaChatLieu = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTenChatLieu = new javax.swing.JTextField();
        bttThemChatLieu = new javax.swing.JButton();
        bttSua = new javax.swing.JButton();
        txtTimChatLIeu = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblChatLieu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel18.setText("Chất liệu sản phẩm");

        jLabel19.setText("Mã chất liệu:");

        jLabel20.setText("Tên chất liệu:");

        bttThemChatLieu.setBackground(new java.awt.Color(0, 255, 0));
        bttThemChatLieu.setText("Thêm");
        bttThemChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThemChatLieuActionPerformed(evt);
            }
        });

        bttSua.setBackground(new java.awt.Color(255, 255, 51));
        bttSua.setText("Sửa");
        bttSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSuaActionPerformed(evt);
            }
        });

        txtTimChatLIeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimChatLIeuKeyReleased(evt);
            }
        });

        jLabel28.setText("Tìm tên :");

        tblChatLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã chất liệu", "Tên chất liệu"
            }
        ));
        tblChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChatLieuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblChatLieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMaChatLieu))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bttThemChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bttSua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtTenChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtTimChatLIeu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttThemChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimChatLIeu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttThemChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThemChatLieuActionPerformed
        // TODO add your handling code here:
        if (valideteChatLieu()) {
            ChatLieuRepository mr = new ChatLieuRepository();
            if (mr.getMaChatLieu(txtMaChatLieu.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Mã chất liệu đã tồn tại");
            } else {
                ChatLieu cl = getInputChatLieu();
                if (chatLieuService.addSP(cl) != null) {
                    JOptionPane.showMessageDialog(this, "OK");
                    loadTableChatLieu();
                } else {
                    JOptionPane.showMessageDialog(this, "Fails");
                }
    }//GEN-LAST:event_bttThemChatLieuActionPerformed
        }
    }
    private void bttSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSuaActionPerformed
        // TODO add your handling code here:
        if (valideteChatLieu()) {
            index = tblChatLieu.getSelectedRow();
            ChatLieu cl = getInputChatLieu();
            if (chatLieuService.updateSP(cl, chatLieuService.getAll().get(index).getId()) > 0) {
                JOptionPane.showMessageDialog(this, "OK");
            } else {
                JOptionPane.showMessageDialog(this, "Fails");
            }
            loadTableChatLieu();
            resetInputSPCL();
        }
    }//GEN-LAST:event_bttSuaActionPerformed

    private void txtTimChatLIeuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimChatLIeuKeyReleased
        // TODO add your handling code here:

        this.fillTableTimChatLieu(chatLieuService.timcl(txtTimChatLIeu.getText()));
    }//GEN-LAST:event_txtTimChatLIeuKeyReleased

    private void tblChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChatLieuMouseClicked
        // TODO add your handling code here:
        showDetailsChatLieu();
    }//GEN-LAST:event_tblChatLieuMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttSua;
    private javax.swing.JButton bttThemChatLieu;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblChatLieu;
    private javax.swing.JTextField txtMaChatLieu;
    private javax.swing.JTextField txtTenChatLieu;
    private javax.swing.JTextField txtTimChatLIeu;
    // End of variables declaration//GEN-END:variables
      boolean valideteChatLieu() {
        if (txtMaChatLieu.getText().isBlank() || txtTenChatLieu.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống dữ liệu");
            return false;
        }
        return true;
    }

    private void loadTableChatLieu() {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblChatLieu.getModel();

        model.setRowCount(0);
        List<ChatLieu> list = chatLieuService.getAll();

        for (ChatLieu chatLieu : list) {
            model.addRow(new Object[]{
                chatLieu.getMaChatLieu(),
                chatLieu.getTenChatLieu()
            });
        }
    }

    private void showDetailsChatLieu() {
        Integer row = tblChatLieu.getSelectedRow();
        txtMaChatLieu.setText((String) tblChatLieu.getValueAt(row, 0));
        txtTenChatLieu.setText((String) tblChatLieu.getValueAt(row, 1));
    }

    public ChatLieu getInputChatLieu() {
        ChatLieu cl = new ChatLieu();
        cl.setMaChatLieu(txtMaChatLieu.getText());
        cl.setTenChatLieu(txtTenChatLieu.getText());
        return cl;
    }

    void fillTableTimChatLieu(List<ChatLieu> list) {
        DefaultTableModel tblModel = new DefaultTableModel();
        tblModel = (DefaultTableModel) tblChatLieu.getModel();
        tblModel.setRowCount(0);
        for (ChatLieu cl : list) {
            Object toDataRow[] = {cl.getMaChatLieu(), cl.getTenChatLieu(),};
            tblModel.addRow(toDataRow);
        }
    }

}
